
class Bag:
    def __init__(self, tiles):
        self.tiles = tiles
    def __str__(self):
        return str(self.tiles)
    def return_to_bag(self, tile):
        return self.tiles.append(tile)

    def remove_from_bag(self, tile):
        return self.tiles.remove(tile)

en_bag = Bag(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd', 'd', 'd', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'f', 'f', 'g', 'g', 'g', 'h', 'h', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'k', 'l', 'l', 'l', 'l', 'm', 'm', 'n', 'n', 'n', 'n', 'n', 'n', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'q', 'r', 'r', 'r', 'r', 'r', 'r', 's', 's', 's', 's', 't', 't', 't', 't', 't', 't', 'u', 'u', 'u', 'u', 'v', 'v', 'w', 'w', 'x', 'y', 'y', 'z']) # создаем массив сумка букв
ru_bag = Bag(['а', 'а', 'а', 'а', 'а', 'а', 'а', 'а', 'б', 'б', 'в', 'в', 'в', 'в', 'г', 'г', 'д', 'д', 'д', 'д', 'е', 'е', 'е', 'е', 'е', 'е', 'е', 'е', 'ё', 'ж', 'з', 'з', 'и', 'и', 'и', 'и', 'и', 'й', 'к', 'к', 'к', 'к', 'л', 'л', 'л', 'л', 'м', 'м', 'м', 'н', 'н', 'н', 'н', 'н', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'п', 'п', 'п', 'п', 'р', 'р', 'р', 'р', 'р', 'с', 'с', 'с', 'с', 'с', 'т', 'т', 'т', 'т', 'т', 'у', 'у', 'у', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ы', 'ь', 'ь', 'э', 'ю', 'я', 'я'])
est_bag = Bag(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd', 'd', 'd', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'f', 'f', 'g', 'g', 'g', 'h', 'h', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'k', 'l', 'l', 'l', 'l', 'm', 'm', 'n', 'n', 'n', 'n', 'n', 'n', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'r', 'r', 'r', 'r', 'r', 'r', 's', 's', 's', 's', 'š', 'z', 'ž', 't', 't', 't', 't', 't', 't', 'u', 'u', 'u', 'u', 'v', 'v', 'õ', 'õ', 'ä', 'ä', 'ö', 'ö', 'ü', 'ü', 'x', 'x', 'y', 'y'])

# print(en_bag)
# en_bag.remove_from_bag('a')
# print(en_bag)
# def add_to_en_bag(tile, quantity): # добавляем буквы и количество букв в сумку 
#     for _ in range(quantity):
#         en_bag.append(tile)

# add_to_en_bag('a', 9)
# add_to_en_bag('b', 2)
# add_to_en_bag('c', 2)
# add_to_en_bag('d', 4)
# add_to_en_bag('e', 12)
# add_to_en_bag('f', 2)
# add_to_en_bag('g', 3)
# add_to_en_bag('h', 2)
# add_to_en_bag('i', 9)
# add_to_en_bag('j', 9)
# add_to_en_bag('k', 1)
# add_to_en_bag('l', 4)
# add_to_en_bag('m', 2)
# add_to_en_bag('n', 6)
# add_to_en_bag('o', 8)
# add_to_en_bag('p', 2)
# add_to_en_bag('q', 1)
# add_to_en_bag('r', 6)
# add_to_en_bag('s', 4)
# add_to_en_bag('t', 6)
# add_to_en_bag('u', 4)
# add_to_en_bag('v', 2)
# add_to_en_bag('w', 2)
# add_to_en_bag('x', 1)
# add_to_en_bag('y', 2)
# add_to_en_bag('z', 1)
#add_to_bag('#', 2)

# def add_to_est_bag(tile, quantity): # добавляем буквы и количество букв в сумку 
#     for _ in range(quantity):
#         est_bag.append(tile)
# add_to_est_bag('a', 9)
# add_to_est_bag('b', 2)
# add_to_est_bag('c', 2)
# add_to_est_bag('d', 4)
# add_to_est_bag('e', 12)
# add_to_est_bag('f', 2)
# add_to_est_bag('g', 3)
# add_to_est_bag('h', 2)
# add_to_est_bag('i', 9)
# add_to_est_bag('j', 9)
# add_to_est_bag('k', 1)
# add_to_est_bag('l', 4)
# add_to_est_bag('m', 2)
# add_to_est_bag('n', 6)
# add_to_est_bag('o', 8)
# add_to_est_bag('p', 2)
# add_to_est_bag('r', 6)
# add_to_est_bag('s', 4)
# add_to_est_bag('š', 1)
# add_to_est_bag('z', 1)        
# add_to_est_bag('ž', 1)        
# add_to_est_bag('t', 6)
# add_to_est_bag('u', 4)
# add_to_est_bag('v', 2)
# add_to_est_bag('õ', 2)
# add_to_est_bag('ä', 2)
# add_to_est_bag('ö', 2)
# add_to_est_bag('ü', 2)
# add_to_est_bag('x', 2)
# add_to_est_bag('y', 2)


# def add_to_ru_bag(tile, quantity): # добавляем буквы и количество букв в сумку 
#     for _ in range(quantity):
#         ru_bag.append(tile)
# add_to_ru_bag("а", 8)
# add_to_ru_bag("б", 2)
# add_to_ru_bag("в", 4)
# add_to_ru_bag("г", 2)
# add_to_ru_bag("д", 4)
# add_to_ru_bag("е", 8)
# add_to_ru_bag("ё", 1)
# add_to_ru_bag("ж", 1)
# add_to_ru_bag("з", 2)
# add_to_ru_bag("и", 5)
# add_to_ru_bag("й", 1)
# add_to_ru_bag("к", 4)
# add_to_ru_bag("л", 4)
# add_to_ru_bag("м", 3)
# add_to_ru_bag("н", 5)
# add_to_ru_bag("о", 10)
# add_to_ru_bag("п", 4)
# add_to_ru_bag("р", 5)
# add_to_ru_bag("с", 5)
# add_to_ru_bag("т", 5)
# add_to_ru_bag("у", 4)
# add_to_ru_bag("ф", 1)
# add_to_ru_bag("х", 1)
# add_to_ru_bag("ц", 1)
# add_to_ru_bag("ч", 1)
# add_to_ru_bag("ш", 1)
# add_to_ru_bag("щ", 1)
# add_to_ru_bag("ъ", 1)
# add_to_ru_bag("ы", 2)
# add_to_ru_bag("ь", 2)
# add_to_ru_bag("э", 1)
# add_to_ru_bag("ю", 1)
# add_to_ru_bag("я", 2)


